export const HOME_MEDIA = {
  heroSlides: [
    {
      id: 'tilla-piece',
      src: '/images/products/tilla/tilla1-main.jpg',
      alt: 'A Poshkaar Tilla embroidered Kashmiri pheran shown as a ready product',
      kind: 'photograph',
      credit: 'Image supplied by Poshkaar',
      eyebrow: 'Shop Kashmir craft',
      title: ['Ready pieces.', 'Made to feel', 'personal.'],
      description: 'Explore embroidered clothing, gifts and home objects with clear prices and WhatsApp guidance.',
      objectPosition: 'center 46%',
      mobileObjectPosition: 'center 38%',
    },
    {
      id: 'aari-piece',
      src: '/images/products/aari/aari1-main.jpg',
      alt: 'A Poshkaar Aari embroidered Kashmiri pheran product',
      kind: 'photograph',
      credit: 'Image supplied by Poshkaar',
      eyebrow: 'New arrivals',
      title: ['Wear Kashmir', 'with quiet', 'detail.'],
      description: 'Browse Aari, Tilla, Dabka and Zari pieces selected for occasion wear and gifting.',
      objectPosition: 'center 44%',
      mobileObjectPosition: 'center 36%',
    },
    {
      id: 'dabka-piece',
      src: '/images/products/dabka/dabka1-main.jpg',
      alt: 'A Poshkaar Dabka embroidered Kashmiri ensemble shown as a product',
      kind: 'photograph',
      credit: 'Image supplied by Poshkaar',
      eyebrow: 'Occasion wear',
      title: ['For weddings,', 'gifts and', 'winter days.'],
      description: 'Choose from Dabka, Tilla, Aari and Zari pieces with guidance before you buy.',
      objectPosition: 'center 46%',
      mobileObjectPosition: 'center 38%',
    },
    {
      id: 'zari-piece',
      src: '/images/products/zari/zari1-main.jpg',
      alt: 'A Poshkaar Zari embroidered Kashmiri product shown for sale',
      kind: 'photograph',
      credit: 'Image supplied by Poshkaar',
      eyebrow: 'Gift edit',
      title: ['Handwork that', 'arrives with', 'context.'],
      description: 'Every product page keeps price, care, material and custom order details close.',
      objectPosition: 'center 46%',
      mobileObjectPosition: 'center 38%',
    },
    {
      id: 'pashmina-piece',
      src: '/images/products/tilla/tilla5-main.jpg',
      alt: 'A Poshkaar embroidered pashmina wrap product displayed for shopping',
      kind: 'photograph',
      credit: 'Image supplied by Poshkaar',
      eyebrow: 'Ready to browse',
      title: ['Wraps, sets', 'and pieces', 'to gift.'],
      description: 'Shop across Poshkaar categories or ask us on WhatsApp before you order.',
      objectPosition: 'center 46%',
      mobileObjectPosition: 'center 38%',
    },
  ],
  categories: {
    pashmina: {
      src: '/images/home/pashmina-jamawar-shawl.jpeg',
      alt: 'A fine Jamawar shawl displayed on a wooden hanger',
      kind: 'photograph',
    },
    walnut: {
      src: '/images/home/walnut-wood-carving.jpeg',
      alt: 'A Kashmiri wood carver working on a walnut wood box',
      kind: 'photograph',
    },
    papier: {
      src: '/images/home/papier-mache-vases.webp',
      alt: 'Hand-painted papier-mache vases and boxes in a Kashmir shop',
      kind: 'photograph',
    },
    copper: {
      src: '/images/home/kashmiri-copper-samovar.jpg',
      alt: 'A traditional engraved copper samovar in a Srinagar tea shop',
      kind: 'photograph',
      objectPosition: '58% center',
      credit: {
        name: 'Gannu03',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Samovar_from_Kashmir.jpg',
        licenseName: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
      },
    },
    willow: {
      src: '/images/home/willow-wicker-baskets.jpeg',
      alt: 'A market display of handwoven willow baskets',
      kind: 'photograph',
    },
  },
  collections: {
    newArrivals: {
      src: '/images/aari.jpg',
      alt: 'A close view of colourful Aari embroidery on cloth',
      kind: 'photograph',
    },
    wedding: {
      src: '/images/tila.jpg',
      alt: 'A deep red shawl finished with gold Tilla embroidery',
      kind: 'photograph',
    },
    pashmina: {
      src: '/images/home/pashmina-sozni-jamawar.jpeg',
      alt: 'A close view of detailed Sozni work on a Pashmina textile',
      kind: 'photograph',
    },
    signature: {
      src: '/images/product2.jpg',
      alt: 'A patterned shawl displayed in natural room light',
      kind: 'photograph',
    },
  },
  heritage: {
    artisan: {
      src: '/images/home/walnut-carver-workshop.webp',
      alt: 'A Kashmiri walnut wood artisan carving by hand in a workshop',
      kind: 'photograph',
    },
  },
  visualEdit: {
    gathering: {
      src: '/images/home/culture-gathering.webp',
      alt: 'Three women in traditional Kashmiri clothing seated together with textiles',
      kind: 'photograph',
    },
    copper: {
      src: '/images/home/copper-plate-portrait.webp',
      alt: 'A woman holding a large engraved Kashmiri copper plate',
      kind: 'photograph',
    },
    willow: {
      src: '/images/home/willow-basket-detail.webp',
      alt: 'A woman in an embroidered pheran holding a handwoven willow basket',
      kind: 'photograph',
    },
    lake: {
      src: '/images/home/dal-lake-hazratbal.webp',
      alt: 'Dal Lake, Hazratbal shrine and snow-covered Kashmir mountains',
      kind: 'photograph',
    },
    loom: {
      src: '/images/home/loom-artisan.webp',
      alt: 'A Kashmiri artisan working at a loom in natural workshop light',
      kind: 'photograph',
    },
  },
  journal: {
    slowHandwork: {
      src: '/images/artists.jpg',
      alt: 'Hands sewing fine embroidery into a textile',
      kind: 'photograph',
    },
    materialGuide: {
      src: '/images/gess.jpg',
      alt: 'Hands guiding coloured thread through a traditional weave',
      kind: 'photograph',
    },
    productDetails: {
      src: '/images/dabka.jpg',
      alt: 'A close view of metal thread and bead handwork',
      kind: 'photograph',
    },
  },
};

export const HOME_IMAGE_ENTRIES = [
  ...HOME_MEDIA.heroSlides.map((media) => [`hero.${media.id}`, media]),
  ...Object.entries(HOME_MEDIA.categories).map(([name, media]) => [`category.${name}`, media]),
  ...Object.entries(HOME_MEDIA.collections).map(([name, media]) => [`collection.${name}`, media]),
  ...Object.entries(HOME_MEDIA.heritage).map(([name, media]) => [`heritage.${name}`, media]),
  ...Object.entries(HOME_MEDIA.visualEdit).map(([name, media]) => [`visualEdit.${name}`, media]),
  ...Object.entries(HOME_MEDIA.journal).map(([name, media]) => [`journal.${name}`, media]),
];
