export const HOME_MEDIA = {
  heroSlides: [
    {
      id: 'tilla-piece',
      src: '/images/products/tilla/tilla1-main.jpg',
      alt: 'A Poshkaar Tilla embroidered Kashmiri pheran shown as a ready product',
      kind: 'photograph',
      credit: 'Image supplied by Poshkaar',
      eyebrow: 'Shop Kashmir craft',
      title: ['Ready pieces.', 'Made to feel', 'personal.'],
      description: 'Explore embroidered clothing, gifts and home objects with clear prices and WhatsApp guidance.',
      objectPosition: 'center 46%',
      mobileObjectPosition: 'center 38%',
    },
    {
      id: 'walnut-object',
      src: '/images/product-walnut-keepsake-box.jpg',
      alt: 'A carved Kashmiri walnut wood keepsake box from Poshkaar',
      kind: 'photograph',
      credit: 'Image supplied by Poshkaar',
      eyebrow: 'Walnut wood',
      title: ['Carved objects', 'for considered', 'homes.'],
      description: 'Shop Kashmiri walnut wood pieces with size, care and gifting guidance before dispatch.',
      objectPosition: 'center 52%',
      mobileObjectPosition: 'center 44%',
    },
    {
      id: 'papier-object',
      src: '/images/product-papier-mache-vase.jpg',
      alt: 'A hand-painted Kashmiri papier mache vase from Poshkaar',
      kind: 'photograph',
      credit: 'Image supplied by Poshkaar',
      eyebrow: 'Papier mache',
      title: ['Painted colour', 'made for', 'gifting.'],
      description: 'Browse hand-painted papier mache objects with clear finish, care and availability notes.',
      objectPosition: 'center 50%',
      mobileObjectPosition: 'center 42%',
    },
    {
      id: 'copper-object',
      src: '/images/product-copper-samovar.jpg',
      alt: 'An engraved Kashmiri copper samovar from Poshkaar',
      kind: 'photograph',
      credit: 'Image supplied by Poshkaar',
      eyebrow: 'Copperware',
      title: ['Warm metal', 'with hand', 'engraving.'],
      description: 'Discover engraved copperware with current-piece photographs, care and food-use guidance.',
      objectPosition: 'center 52%',
      mobileObjectPosition: 'center 44%',
    },
    {
      id: 'willow-object',
      src: '/images/product-willow-basket.jpg',
      alt: 'A handwoven Kashmiri willow wicker basket from Poshkaar',
      kind: 'photograph',
      credit: 'Image supplied by Poshkaar',
      eyebrow: 'Willow wicker',
      title: ['Woven forms', 'for everyday', 'use.'],
      description: 'Shop willow baskets and useful home pieces, or ask on WhatsApp before you order.',
      objectPosition: 'center 52%',
      mobileObjectPosition: 'center 44%',
    },
  ],
  categories: {
    pashmina: {
      src: '/images/home/pashmina-jamawar-shawl.jpeg',
      alt: 'A fine Jamawar shawl displayed on a wooden hanger',
      kind: 'photograph',
    },
    walnut: {
      src: '/images/home/walnut-wood-carving.jpeg',
      alt: 'A Kashmiri wood carver working on a walnut wood box',
      kind: 'photograph',
    },
    papier: {
      src: '/images/home/papier-mache-vases.webp',
      alt: 'Hand-painted papier-mache vases and boxes in a Kashmir shop',
      kind: 'photograph',
    },
    copper: {
      src: '/images/home/kashmiri-copper-samovar.jpg',
      alt: 'A traditional engraved copper samovar in a Srinagar tea shop',
      kind: 'photograph',
      objectPosition: '58% center',
      credit: {
        name: 'Gannu03',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Samovar_from_Kashmir.jpg',
        licenseName: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
      },
    },
    willow: {
      src: '/images/home/willow-wicker-baskets.jpeg',
      alt: 'A market display of handwoven willow baskets',
      kind: 'photograph',
    },
  },
  collections: {
    newArrivals: {
      src: '/images/aari.jpg',
      alt: 'A close view of colourful Aari embroidery on cloth',
      kind: 'photograph',
    },
    wedding: {
      src: '/images/tila.jpg',
      alt: 'A deep red shawl finished with gold Tilla embroidery',
      kind: 'photograph',
    },
    pashmina: {
      src: '/images/home/pashmina-sozni-jamawar.jpeg',
      alt: 'A close view of detailed Sozni work on a Pashmina textile',
      kind: 'photograph',
    },
    signature: {
      src: '/images/product2.jpg',
      alt: 'A patterned shawl displayed in natural room light',
      kind: 'photograph',
    },
  },
  heritage: {
    artisan: {
      src: '/images/home/walnut-carver-workshop.webp',
      alt: 'A Kashmiri walnut wood artisan carving by hand in a workshop',
      kind: 'photograph',
    },
  },
  visualEdit: {
    gathering: {
      src: '/images/home/culture-gathering.webp',
      alt: 'Three women in traditional Kashmiri clothing seated together with textiles',
      kind: 'photograph',
    },
    copper: {
      src: '/images/home/copper-plate-portrait.webp',
      alt: 'A woman holding a large engraved Kashmiri copper plate',
      kind: 'photograph',
    },
    willow: {
      src: '/images/home/willow-basket-detail.webp',
      alt: 'A woman in an embroidered pheran holding a handwoven willow basket',
      kind: 'photograph',
    },
    lake: {
      src: '/images/home/dal-lake-hazratbal.webp',
      alt: 'Dal Lake, Hazratbal shrine and snow-covered Kashmir mountains',
      kind: 'photograph',
    },
    loom: {
      src: '/images/home/loom-artisan.webp',
      alt: 'A Kashmiri artisan working at a loom in natural workshop light',
      kind: 'photograph',
    },
  },
  journal: {
    slowHandwork: {
      src: '/images/artists.jpg',
      alt: 'Hands sewing fine embroidery into a textile',
      kind: 'photograph',
    },
    materialGuide: {
      src: '/images/gess.jpg',
      alt: 'Hands guiding coloured thread through a traditional weave',
      kind: 'photograph',
    },
    productDetails: {
      src: '/images/dabka.jpg',
      alt: 'A close view of metal thread and bead handwork',
      kind: 'photograph',
    },
  },
};

export const HOME_IMAGE_ENTRIES = [
  ...HOME_MEDIA.heroSlides.map((media) => [`hero.${media.id}`, media]),
  ...Object.entries(HOME_MEDIA.categories).map(([name, media]) => [`category.${name}`, media]),
  ...Object.entries(HOME_MEDIA.collections).map(([name, media]) => [`collection.${name}`, media]),
  ...Object.entries(HOME_MEDIA.heritage).map(([name, media]) => [`heritage.${name}`, media]),
  ...Object.entries(HOME_MEDIA.visualEdit).map(([name, media]) => [`visualEdit.${name}`, media]),
  ...Object.entries(HOME_MEDIA.journal).map(([name, media]) => [`journal.${name}`, media]),
];
