-- Generated from src/lib/catalogProducts.js.
-- Run supabase/schema.sql and supabase/production-commerce-hardening.sql first.
-- This upsert is idempotent: re-running it updates the same 51 catalogue records.

begin;

insert into public.products (
  id,
  title,
  slug,
  sku,
  category,
  collection,
  embroidery_type,
  description,
  price,
  compare_at_price,
  images,
  image,
  sizes,
  colors,
  stock,
  is_bestseller,
  review_count,
  material,
  origin,
  craft,
  care_instructions,
  lead_time,
  made_to_order,
  ready_to_ship,
  limited_edition,
  one_of_one,
  status,
  published,
  seo_title,
  seo_description,
  photography_status
)
values
(
  'aari-01',
  'Ivory Blue Aari Pheran',
  'aari-01',
  'PKM-AARI-01',
  'Kurtis',
  'New Arrivals',
  'Aari',
  'A softly structured Kashmiri silhouette finished with flowing Aari embroidery. Designed for comfortable occasion wear, it can be made to your measurements through our custom order service.',
  12500,
  0,
  '["/images/products/aari/aari1-main.jpg","/images/products/aari/aari1-detail1.jpg"]'::jsonb,
  '/images/products/aari/aari1-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Ivory & blue"]'::jsonb,
  3,
  true,
  0,
  'Wool blend',
  'Kashmir, India',
  'Aari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 10–14 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Ivory Blue Aari Pheran | Poshkaar Kashmir',
  'Ivory & blue Aari embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'aari-02',
  'Charcoal Meadow Aari Pheran',
  'aari-02',
  'PKM-AARI-02',
  'Kurtis',
  'Aari Edit',
  'Aari',
  'A softly structured Kashmiri silhouette finished with flowing Aari embroidery. Designed for comfortable occasion wear, it can be made to your measurements through our custom order service.',
  13500,
  0,
  '["/images/products/aari/aari2-main.jpg","/images/products/aari/aari2-detail1.jpg"]'::jsonb,
  '/images/products/aari/aari2-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Charcoal"]'::jsonb,
  3,
  false,
  0,
  'Wool blend',
  'Kashmir, India',
  'Aari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 10–14 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Charcoal Meadow Aari Pheran | Poshkaar Kashmir',
  'Charcoal Aari embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'aari-03',
  'Crimson Garden Aari Pheran',
  'aari-03',
  'PKM-AARI-03',
  'Kurtis',
  'New Arrivals',
  'Aari',
  'A softly structured Kashmiri silhouette finished with flowing Aari embroidery. Designed for comfortable occasion wear, it can be made to your measurements through our custom order service.',
  14500,
  0,
  '["/images/products/aari/aari3-main.jpg","/images/products/aari/aari3-detail1.jpg"]'::jsonb,
  '/images/products/aari/aari3-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Crimson"]'::jsonb,
  3,
  true,
  0,
  'Wool blend',
  'Kashmir, India',
  'Aari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 10–14 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Crimson Garden Aari Pheran | Poshkaar Kashmir',
  'Crimson Aari embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'aari-04',
  'Cobalt Gold Aari Pheran',
  'aari-04',
  'PKM-AARI-04',
  'Kurtis',
  'Aari Edit',
  'Aari',
  'A softly structured Kashmiri silhouette finished with flowing Aari embroidery. Designed for comfortable occasion wear, it can be made to your measurements through our custom order service.',
  14500,
  0,
  '["/images/products/aari/aari4-main.jpg","/images/products/aari/aari4-detail1.jpg"]'::jsonb,
  '/images/products/aari/aari4-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Cobalt blue"]'::jsonb,
  3,
  false,
  0,
  'Wool blend',
  'Kashmir, India',
  'Aari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 10–14 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Cobalt Gold Aari Pheran | Poshkaar Kashmir',
  'Cobalt blue Aari embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'aari-05',
  'Ivory Rose Aari Pheran',
  'aari-05',
  'PKM-AARI-05',
  'Kurtis',
  'Aari Edit',
  'Aari',
  'A softly structured Kashmiri silhouette finished with flowing Aari embroidery. Designed for comfortable occasion wear, it can be made to your measurements through our custom order service.',
  12500,
  0,
  '["/images/products/aari/aari5-main.jpg","/images/products/aari/aari5-detail1.jpg"]'::jsonb,
  '/images/products/aari/aari5-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Ivory & rose"]'::jsonb,
  3,
  false,
  0,
  'Wool blend',
  'Kashmir, India',
  'Aari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 10–14 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Ivory Rose Aari Pheran | Poshkaar Kashmir',
  'Ivory & rose Aari embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'aari-06',
  'Ivory Indigo Aari Pheran',
  'aari-06',
  'PKM-AARI-06',
  'Kurtis',
  'Aari Edit',
  'Aari',
  'A softly structured Kashmiri silhouette finished with flowing Aari embroidery. Designed for comfortable occasion wear, it can be made to your measurements through our custom order service.',
  12500,
  0,
  '["/images/products/aari/aari6-main.jpg","/images/products/aari/aari6-detail1.jpg"]'::jsonb,
  '/images/products/aari/aari6-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Ivory & indigo"]'::jsonb,
  3,
  false,
  0,
  'Wool blend',
  'Kashmir, India',
  'Aari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 10–14 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Ivory Indigo Aari Pheran | Poshkaar Kashmir',
  'Ivory & indigo Aari embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'aari-07',
  'Sand Garden Aari Pheran',
  'aari-07',
  'PKM-AARI-07',
  'Kurtis',
  'Aari Edit',
  'Aari',
  'A softly structured Kashmiri silhouette finished with flowing Aari embroidery. Designed for comfortable occasion wear, it can be made to your measurements through our custom order service.',
  13500,
  0,
  '["/images/products/aari/aari7-main.jpg","/images/products/aari/aari7-detail1.jpg"]'::jsonb,
  '/images/products/aari/aari7-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Sand"]'::jsonb,
  3,
  false,
  0,
  'Wool blend',
  'Kashmir, India',
  'Aari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 10–14 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Sand Garden Aari Pheran | Poshkaar Kashmir',
  'Sand Aari embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'aari-08',
  'Teal Saffron Aari Pheran',
  'aari-08',
  'PKM-AARI-08',
  'Kurtis',
  'New Arrivals',
  'Aari',
  'A softly structured Kashmiri silhouette finished with flowing Aari embroidery. Designed for comfortable occasion wear, it can be made to your measurements through our custom order service.',
  14500,
  0,
  '["/images/products/aari/aari8-main.jpg","/images/products/aari/aari8-detail1.jpg"]'::jsonb,
  '/images/products/aari/aari8-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Teal & saffron"]'::jsonb,
  3,
  true,
  0,
  'Wool blend',
  'Kashmir, India',
  'Aari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 10–14 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Teal Saffron Aari Pheran | Poshkaar Kashmir',
  'Teal & saffron Aari embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'aari-09',
  'Ivory Garnet Aari Kurta',
  'aari-09',
  'PKM-AARI-09',
  'Kurtis',
  'Aari Edit',
  'Aari',
  'A softly structured Kashmiri silhouette finished with flowing Aari embroidery. Designed for comfortable occasion wear, it can be made to your measurements through our custom order service.',
  15500,
  0,
  '["/images/products/aari/aari9-main.jpg","/images/products/aari/aari9-detail1.jpg"]'::jsonb,
  '/images/products/aari/aari9-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Ivory & garnet"]'::jsonb,
  3,
  false,
  0,
  'Wool blend',
  'Kashmir, India',
  'Aari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 10–14 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Ivory Garnet Aari Kurta | Poshkaar Kashmir',
  'Ivory & garnet Aari embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'aari-10',
  'Aubergine Sage Aari Kurta',
  'aari-10',
  'PKM-AARI-10',
  'Kurtis',
  'Aari Edit',
  'Aari',
  'A softly structured Kashmiri silhouette finished with flowing Aari embroidery. Designed for comfortable occasion wear, it can be made to your measurements through our custom order service.',
  15500,
  0,
  '["/images/products/aari/aari10-main.jpg","/images/products/aari/aari10-detail1.jpg","/images/products/aari/aari10-detail2.jpg"]'::jsonb,
  '/images/products/aari/aari10-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Aubergine"]'::jsonb,
  3,
  false,
  0,
  'Wool blend',
  'Kashmir, India',
  'Aari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 10–14 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Aubergine Sage Aari Kurta | Poshkaar Kashmir',
  'Aubergine Aari embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'tilla-01',
  'Graphite Copper Tilla Pheran',
  'tilla-01',
  'PKM-TILLA-01',
  'Kurtis',
  'New Arrivals',
  'Tilla',
  'A refined Kashmiri ensemble enriched with metallic Tilla embroidery. The relaxed shape balances ceremonial detail with an easy, modern fit and can be customised to your measurements.',
  21500,
  0,
  '["/images/products/tilla/tilla1-main.jpg","/images/products/tilla/tilla1-detail1.jpg","/images/products/tilla/tilla1-detail2.jpg","/images/products/tilla/tilla1-detail3.jpg"]'::jsonb,
  '/images/products/tilla/tilla1-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Graphite & copper"]'::jsonb,
  3,
  true,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Tilla',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Graphite Copper Tilla Pheran | Poshkaar Kashmir',
  'Graphite & copper Tilla embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'tilla-02',
  'Cinnamon Silver Tilla Pheran',
  'tilla-02',
  'PKM-TILLA-02',
  'Kurtis',
  'Tilla Edit',
  'Tilla',
  'A refined Kashmiri ensemble enriched with metallic Tilla embroidery. The relaxed shape balances ceremonial detail with an easy, modern fit and can be customised to your measurements.',
  19500,
  0,
  '["/images/products/tilla/tilla2-main.jpg","/images/products/tilla/tilla2-detail1.jpg","/images/products/tilla/tilla2-detail2.jpg"]'::jsonb,
  '/images/products/tilla/tilla2-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Cinnamon"]'::jsonb,
  3,
  false,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Tilla',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Cinnamon Silver Tilla Pheran | Poshkaar Kashmir',
  'Cinnamon Tilla embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'tilla-03',
  'Emerald Silver Tilla Ensemble',
  'tilla-03',
  'PKM-TILLA-03',
  'Bridal',
  'New Arrivals',
  'Tilla',
  'A refined Kashmiri ensemble enriched with metallic Tilla embroidery. The relaxed shape balances ceremonial detail with an easy, modern fit and can be customised to your measurements.',
  24500,
  0,
  '["/images/products/tilla/tilla3-main.jpg","/images/products/tilla/tilla3-detail1.jpg","/images/products/tilla/tilla3-detail2.jpg"]'::jsonb,
  '/images/products/tilla/tilla3-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Emerald"]'::jsonb,
  3,
  true,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Tilla',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Emerald Silver Tilla Ensemble | Poshkaar Kashmir',
  'Emerald Tilla embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'tilla-04',
  'Garnet Silver Tilla Ensemble',
  'tilla-04',
  'PKM-TILLA-04',
  'Kurtis',
  'Tilla Edit',
  'Tilla',
  'A refined Kashmiri ensemble enriched with metallic Tilla embroidery. The relaxed shape balances ceremonial detail with an easy, modern fit and can be customised to your measurements.',
  22500,
  0,
  '["/images/products/tilla/tilla4-main.jpg","/images/products/tilla/tilla4-detail1.jpg","/images/products/tilla/tilla4-detail2.jpg"]'::jsonb,
  '/images/products/tilla/tilla4-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Garnet"]'::jsonb,
  3,
  false,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Tilla',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Garnet Silver Tilla Ensemble | Poshkaar Kashmir',
  'Garnet Tilla embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'tilla-05',
  'Ruby Tilla Pashmina Wrap',
  'tilla-05',
  'PKM-TILLA-05',
  'Pashmina',
  'Tilla Edit',
  'Tilla',
  'A generous ruby wrap framed with metallic Tilla embroidery. The one-size drape is designed for winter occasions, bridal trousseaux and meaningful gifting.',
  18500,
  0,
  '["/images/products/tilla/tilla5-main.jpg","/images/products/tilla/tilla5-detail1.jpg","/images/products/tilla/tilla5-detail2.jpg"]'::jsonb,
  '/images/products/tilla/tilla5-main.jpg',
  '["One Size"]'::jsonb,
  '["Ruby red"]'::jsonb,
  3,
  false,
  0,
  'Pashmina blend',
  'Kashmir, India',
  'Tilla',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Ruby Tilla Pashmina Wrap | Poshkaar Kashmir',
  'Ruby red Tilla embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'tilla-06',
  'Plum Silver Tilla Ensemble',
  'tilla-06',
  'PKM-TILLA-06',
  'Kurtis',
  'Tilla Edit',
  'Tilla',
  'A refined Kashmiri ensemble enriched with metallic Tilla embroidery. The relaxed shape balances ceremonial detail with an easy, modern fit and can be customised to your measurements.',
  22500,
  0,
  '["/images/products/tilla/tilla6-main.jpg","/images/products/tilla/tilla6-detail1.jpg"]'::jsonb,
  '/images/products/tilla/tilla6-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Plum"]'::jsonb,
  3,
  false,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Tilla',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Plum Silver Tilla Ensemble | Poshkaar Kashmir',
  'Plum Tilla embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'tilla-07',
  'Aqua Rose Tilla Ensemble',
  'tilla-07',
  'PKM-TILLA-07',
  'Kurtis',
  'Tilla Edit',
  'Tilla',
  'A refined Kashmiri ensemble enriched with metallic Tilla embroidery. The relaxed shape balances ceremonial detail with an easy, modern fit and can be customised to your measurements.',
  23500,
  0,
  '["/images/products/tilla/tilla7-main.jpg","/images/products/tilla/tilla7-detail1.jpg"]'::jsonb,
  '/images/products/tilla/tilla7-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Aqua"]'::jsonb,
  3,
  false,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Tilla',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Aqua Rose Tilla Ensemble | Poshkaar Kashmir',
  'Aqua Tilla embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'tilla-08',
  'Ivory Sapphire Tilla Ensemble',
  'tilla-08',
  'PKM-TILLA-08',
  'Bridal',
  'New Arrivals',
  'Tilla',
  'A refined Kashmiri ensemble enriched with metallic Tilla embroidery. The relaxed shape balances ceremonial detail with an easy, modern fit and can be customised to your measurements.',
  24500,
  0,
  '["/images/products/tilla/tilla8-main.jpg","/images/products/tilla/tilla8-detail1.jpg","/images/products/tilla/tilla8-detail2.jpg"]'::jsonb,
  '/images/products/tilla/tilla8-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Ivory & sapphire"]'::jsonb,
  3,
  true,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Tilla',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Ivory Sapphire Tilla Ensemble | Poshkaar Kashmir',
  'Ivory & sapphire Tilla embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'tilla-09',
  'Teal Copper Tilla Ensemble',
  'tilla-09',
  'PKM-TILLA-09',
  'Kurtis',
  'Tilla Edit',
  'Tilla',
  'A refined Kashmiri ensemble enriched with metallic Tilla embroidery. The relaxed shape balances ceremonial detail with an easy, modern fit and can be customised to your measurements.',
  23500,
  0,
  '["/images/products/tilla/tilla9-main.jpg","/images/products/tilla/tilla9-detail1.jpg"]'::jsonb,
  '/images/products/tilla/tilla9-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Teal & copper"]'::jsonb,
  3,
  false,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Tilla',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Teal Copper Tilla Ensemble | Poshkaar Kashmir',
  'Teal & copper Tilla embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'tilla-10',
  'Burgundy Silver Tilla Ensemble',
  'tilla-10',
  'PKM-TILLA-10',
  'Kurtis',
  'Tilla Edit',
  'Tilla',
  'A refined Kashmiri ensemble enriched with metallic Tilla embroidery. The relaxed shape balances ceremonial detail with an easy, modern fit and can be customised to your measurements.',
  22500,
  0,
  '["/images/products/tilla/tilla10-main.jpg","/images/products/tilla/tilla10-detail1.jpg","/images/products/tilla/tilla10-detail2.jpg","/images/products/tilla/tilla10-detail3.jpg"]'::jsonb,
  '/images/products/tilla/tilla10-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Burgundy"]'::jsonb,
  3,
  false,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Tilla',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Burgundy Silver Tilla Ensemble | Poshkaar Kashmir',
  'Burgundy Tilla embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'dabka-01',
  'Midnight Fuchsia Dabka Ensemble',
  'dabka-01',
  'PKM-DABKA-01',
  'Kurtis',
  'New Arrivals',
  'Dabka',
  'An occasion ensemble finished with dimensional Dabka embroidery and a clean, elongated silhouette. Each piece is prepared to order and can be adjusted to your preferred measurements.',
  22500,
  0,
  '["/images/products/dabka/dabka1-main.jpg","/images/products/dabka/dabka1-detail1.jpg","/images/products/dabka/dabka1-detail2.jpg"]'::jsonb,
  '/images/products/dabka/dabka1-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Midnight & fuchsia"]'::jsonb,
  3,
  true,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Dabka',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 18–24 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Midnight Fuchsia Dabka Ensemble | Poshkaar Kashmir',
  'Midnight & fuchsia Dabka embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'dabka-02',
  'Burnished Copper Dabka Ensemble',
  'dabka-02',
  'PKM-DABKA-02',
  'Kurtis',
  'Wedding Edit',
  'Dabka',
  'An occasion ensemble finished with dimensional Dabka embroidery and a clean, elongated silhouette. Each piece is prepared to order and can be adjusted to your preferred measurements.',
  21500,
  0,
  '["/images/products/dabka/dabka2-main.jpg","/images/products/dabka/dabka2-detail1.jpg"]'::jsonb,
  '/images/products/dabka/dabka2-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Burnished copper"]'::jsonb,
  3,
  false,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Dabka',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 18–24 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Burnished Copper Dabka Ensemble | Poshkaar Kashmir',
  'Burnished copper Dabka embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'dabka-03',
  'Saffron Dabka Ensemble',
  'dabka-03',
  'PKM-DABKA-03',
  'Kurtis',
  'Wedding Edit',
  'Dabka',
  'An occasion ensemble finished with dimensional Dabka embroidery and a clean, elongated silhouette. Each piece is prepared to order and can be adjusted to your preferred measurements.',
  19500,
  0,
  '["/images/products/dabka/dabka3-main.jpg","/images/products/dabka/dabka3-detail1.jpg","/images/products/dabka/dabka3-detail2.jpg"]'::jsonb,
  '/images/products/dabka/dabka3-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Saffron"]'::jsonb,
  3,
  false,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Dabka',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 18–24 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Saffron Dabka Ensemble | Poshkaar Kashmir',
  'Saffron Dabka embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'dabka-04',
  'Sand Rose Dabka Ensemble',
  'dabka-04',
  'PKM-DABKA-04',
  'Bridal',
  'Wedding Edit',
  'Dabka',
  'An occasion ensemble finished with dimensional Dabka embroidery and a clean, elongated silhouette. Each piece is prepared to order and can be adjusted to your preferred measurements.',
  24500,
  0,
  '["/images/products/dabka/dabka4-main.jpg","/images/products/dabka/dabka4-detail1.jpg"]'::jsonb,
  '/images/products/dabka/dabka4-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Sand & rose"]'::jsonb,
  3,
  false,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Dabka',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 18–24 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Sand Rose Dabka Ensemble | Poshkaar Kashmir',
  'Sand & rose Dabka embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'dabka-05',
  'Maroon Dabka Ensemble',
  'dabka-05',
  'PKM-DABKA-05',
  'Bridal',
  'New Arrivals',
  'Dabka',
  'An occasion ensemble finished with dimensional Dabka embroidery and a clean, elongated silhouette. Each piece is prepared to order and can be adjusted to your preferred measurements.',
  25500,
  0,
  '["/images/products/dabka/dabka5-main.jpg","/images/products/dabka/dabka5-detail1.jpg"]'::jsonb,
  '/images/products/dabka/dabka5-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Maroon"]'::jsonb,
  3,
  true,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Dabka',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 18–24 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Maroon Dabka Ensemble | Poshkaar Kashmir',
  'Maroon Dabka embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'dabka-06',
  'Forest Dabka Cape',
  'dabka-06',
  'PKM-DABKA-06',
  'Kurtis',
  'Wedding Edit',
  'Dabka',
  'An occasion ensemble finished with dimensional Dabka embroidery and a clean, elongated silhouette. Each piece is prepared to order and can be adjusted to your preferred measurements.',
  23500,
  0,
  '["/images/products/dabka/dabka6-main.jpg","/images/products/dabka/dabka6-detail1.jpg"]'::jsonb,
  '/images/products/dabka/dabka6-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Forest green"]'::jsonb,
  3,
  false,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Dabka',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 18–24 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Forest Dabka Cape | Poshkaar Kashmir',
  'Forest green Dabka embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'dabka-07',
  'Ivory Gold Dabka Pheran',
  'dabka-07',
  'PKM-DABKA-07',
  'Kurtis',
  'Wedding Edit',
  'Dabka',
  'An occasion ensemble finished with dimensional Dabka embroidery and a clean, elongated silhouette. Each piece is prepared to order and can be adjusted to your preferred measurements.',
  21500,
  0,
  '["/images/products/dabka/dabka7-main.jpg","/images/products/dabka/dabka7-detail1.jpg"]'::jsonb,
  '/images/products/dabka/dabka7-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Ivory & gold"]'::jsonb,
  3,
  false,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Dabka',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 18–24 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Ivory Gold Dabka Pheran | Poshkaar Kashmir',
  'Ivory & gold Dabka embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'zari-01',
  'Black Coral Zari Ensemble',
  'zari-01',
  'PKM-ZARI-01',
  'Kurtis',
  'New Arrivals',
  'Zari',
  'A graceful Kashmiri pheran detailed with antique-gold Zari embroidery. The restrained surface work and easy line make it suitable for celebrations, gifting and winter evenings.',
  19500,
  0,
  '["/images/products/zari/zari1-main.jpg","/images/products/zari/zari1-detail1.jpg","/images/products/zari/zari1-detail2.jpg"]'::jsonb,
  '/images/products/zari/zari1-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Black & coral"]'::jsonb,
  3,
  true,
  0,
  'Velvet blend',
  'Kashmir, India',
  'Zari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Black Coral Zari Ensemble | Poshkaar Kashmir',
  'Black & coral Zari embroidery in a relaxed Kashmiri silhouette.',
  'approved'
),
(
  'zari-02',
  'Ivory Antique Gold Zari Pheran',
  'zari-02',
  'PKM-ZARI-02',
  'Kurtis',
  'Zari Edit',
  'Zari',
  'A graceful Kashmiri pheran detailed with antique-gold Zari embroidery. The restrained surface work and easy line make it suitable for celebrations, gifting and winter evenings.',
  18500,
  0,
  '["/images/products/zari/zari2-main.jpg"]'::jsonb,
  '/images/products/zari/zari2-main.jpg',
  '["XS","S","M","L","XL","Custom"]'::jsonb,
  '["Ivory & antique gold"]'::jsonb,
  3,
  false,
  0,
  'Wool blend',
  'Kashmir, India',
  'Zari',
  'Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.',
  'Made to order in 14–18 business days',
  true,
  false,
  true,
  false,
  'active',
  true,
  'Ivory Antique Gold Zari Pheran | Poshkaar Kashmir',
  'Ivory & antique gold Zari embroidery in a relaxed Kashmiri silhouette.',
  'pending'
),
(
  'copper-01',
  'Chinar Naqashi Copper Ewer',
  'copper-01',
  'PKM-COPPER-01',
  'Copperware',
  'Copperware',
  'Copper Engraving',
  'A sculptural copper ewer with a long pouring lip, curved handle and chinar-inspired engraved surface. Its warm antique finish makes it a graceful table object or meaningful wedding gift.',
  8500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/copperware/copper1-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/copperware/copper1-main.jpg',
  '["1.8 L"]'::jsonb,
  '["Antique copper"]'::jsonb,
  4,
  true,
  0,
  'Copper with engraved antique finish',
  'Kashmir, India',
  'Naqashi Copperware',
  'Wipe with a soft dry cloth and keep dry. Avoid abrasives, dishwashers and acidic cleaners. Natural patina is expected. Confirm food-use guidance for the exact piece before use.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Chinar Naqashi Copper Ewer | Poshkaar Kashmir',
  'Chinar Naqashi Copper Ewer with chinar-inspired hand-engraved detail and an antique copper finish.',
  'pending'
),
(
  'copper-02',
  'Chinar Naqashi Lidded Serving Dish',
  'copper-02',
  'PKM-COPPER-02',
  'Copperware',
  'Copperware',
  'Copper Engraving',
  'A round copper serving dish paired with a matching domed lid. Dense engraved leaf work continues across the interior and cover for a ceremonial, heirloom-led presentation.',
  6800,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/copperware/copper2-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/copperware/copper2-main.jpg',
  '["30 cm"]'::jsonb,
  '["Antique copper"]'::jsonb,
  3,
  false,
  0,
  'Copper with engraved antique finish',
  'Kashmir, India',
  'Naqashi Copperware',
  'Wipe with a soft dry cloth and keep dry. Avoid abrasives, dishwashers and acidic cleaners. Natural patina is expected. Confirm food-use guidance for the exact piece before use.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Chinar Naqashi Lidded Serving Dish | Poshkaar Kashmir',
  'Chinar Naqashi Lidded Serving Dish with chinar-inspired hand-engraved detail and an antique copper finish.',
  'pending'
),
(
  'copper-03',
  'Chinar Naqashi Copper Keepsake Box',
  'copper-03',
  'PKM-COPPER-03',
  'Copperware',
  'Copperware',
  'Copper Engraving',
  'A low-footed copper keepsake box with a removable engraved lid and gently scalloped edges. Designed for jewellery, letters or gifting, with natural variation in every hand-finished surface.',
  5800,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/copperware/copper3-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/copperware/copper3-main.jpg',
  '["24 cm"]'::jsonb,
  '["Antique copper"]'::jsonb,
  4,
  false,
  0,
  'Copper with engraved antique finish',
  'Kashmir, India',
  'Naqashi Copperware',
  'Wipe with a soft dry cloth and keep dry. Avoid abrasives, dishwashers and acidic cleaners. Natural patina is expected. Confirm food-use guidance for the exact piece before use.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Chinar Naqashi Copper Keepsake Box | Poshkaar Kashmir',
  'Chinar Naqashi Copper Keepsake Box with chinar-inspired hand-engraved detail and an antique copper finish.',
  'pending'
),
(
  'copper-04',
  'Chinar Naqashi Copper Bowl Trio',
  'copper-04',
  'PKM-COPPER-04',
  'Copperware',
  'Copperware',
  'Copper Engraving',
  'Three graduated copper bowls brought together as a coordinated serving or display set. Wide polished rims balance the darkened chinar and floral engraving around each rounded form.',
  7500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/copperware/copper4-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/copperware/copper4-main.jpg',
  '["Set of 3"]'::jsonb,
  '["Antique copper"]'::jsonb,
  3,
  false,
  0,
  'Copper with engraved antique finish',
  'Kashmir, India',
  'Naqashi Copperware',
  'Wipe with a soft dry cloth and keep dry. Avoid abrasives, dishwashers and acidic cleaners. Natural patina is expected. Confirm food-use guidance for the exact piece before use.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Chinar Naqashi Copper Bowl Trio | Poshkaar Kashmir',
  'Chinar Naqashi Copper Bowl Trio with chinar-inspired hand-engraved detail and an antique copper finish.',
  'pending'
),
(
  'copper-05',
  'Kashmir Naqashi Copper Samovar Set',
  'copper-05',
  'PKM-COPPER-05',
  'Copperware',
  'Copperware',
  'Copper Engraving',
  'A statement copper samovar with a domed lid, pedestal warming base, serving tap and two matching cups. The richly engraved set is made for ceremonial tea moments and distinguished gifting.',
  18500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/copperware/copper5-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/copperware/copper5-main.jpg',
  '["3 L"]'::jsonb,
  '["Antique copper"]'::jsonb,
  2,
  true,
  0,
  'Copper with engraved antique finish',
  'Kashmir, India',
  'Naqashi Copperware',
  'Wipe with a soft dry cloth and keep dry. Avoid abrasives, dishwashers and acidic cleaners. Natural patina is expected. Confirm food-use guidance for the exact piece before use.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Kashmir Naqashi Copper Samovar Set | Poshkaar Kashmir',
  'Kashmir Naqashi Copper Samovar Set with chinar-inspired hand-engraved detail and an antique copper finish.',
  'pending'
),
(
  'walnut-01',
  'Birdsong Carved Walnut Keepsake Box',
  'walnut-01',
  'PKM-WALNUT-01',
  'Walnut Wood',
  'Walnut Wood',
  'Walnut Wood Carving',
  'A rectangular walnut keepsake box covered with deep openwork carving of birds, flowers and curling leaves. The fitted lid and warm hand-rubbed finish make it an heirloom home object for letters, jewellery or meaningful gifts.',
  9500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut1-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut1-main.jpg',
  '["28 cm"]'::jsonb,
  '["Natural walnut"]'::jsonb,
  2,
  true,
  0,
  'Kashmiri walnut wood',
  'Kashmir, India',
  'Kashmiri Walnut Wood Carving',
  'Dust with a soft dry cloth. Keep away from water, direct sunlight and strong heat. Do not use household polish or abrasive cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Birdsong Carved Walnut Keepsake Box | Poshkaar Kashmir',
  'Birdsong Carved Walnut Keepsake Box, shaped and carved by hand in natural Kashmiri walnut wood.',
  'pending'
),
(
  'walnut-02',
  'Gul Carved Walnut Lidded Box',
  'walnut-02',
  'PKM-WALNUT-02',
  'Walnut Wood',
  'Walnut Wood',
  'Walnut Wood Carving',
  'A round lidded walnut box with layered leaf carving around the top and a continuous floral band around the body. Its generous form suits dry keepsakes, jewellery or a considered wedding gift.',
  6500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut2-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut2-main.jpg',
  '["24 cm"]'::jsonb,
  '["Natural walnut"]'::jsonb,
  3,
  false,
  0,
  'Kashmiri walnut wood',
  'Kashmir, India',
  'Kashmiri Walnut Wood Carving',
  'Dust with a soft dry cloth. Keep away from water, direct sunlight and strong heat. Do not use household polish or abrasive cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Gul Carved Walnut Lidded Box | Poshkaar Kashmir',
  'Gul Carved Walnut Lidded Box, shaped and carved by hand in natural Kashmiri walnut wood.',
  'pending'
),
(
  'walnut-03',
  'Chinar Carved Walnut Wall Clock',
  'walnut-03',
  'PKM-WALNUT-03',
  'Walnut Wood',
  'Walnut Wood',
  'Walnut Wood Carving',
  'A statement wall clock framed by hand-carved scrolling leaves and warm natural walnut grain. A quiet clock movement and clear hour markers bring daily function to an ornamental Kashmiri woodcraft piece.',
  12500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut3-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut3-main.jpg',
  '["45 cm"]'::jsonb,
  '["Natural walnut"]'::jsonb,
  2,
  true,
  0,
  'Kashmiri walnut wood',
  'Kashmir, India',
  'Kashmiri Walnut Wood Carving',
  'Dust with a soft dry cloth. Keep away from water, direct sunlight and strong heat. Do not use household polish or abrasive cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Chinar Carved Walnut Wall Clock | Poshkaar Kashmir',
  'Chinar Carved Walnut Wall Clock, shaped and carved by hand in natural Kashmiri walnut wood.',
  'pending'
),
(
  'walnut-04',
  'Iris Carved Walnut Wall Panel',
  'walnut-04',
  'PKM-WALNUT-04',
  'Walnut Wood',
  'Walnut Wood',
  'Walnut Wood Carving',
  'A tall arched walnut panel carved with a balanced flowering iris motif. Designed as a slim wall or shelf accent, its restrained relief lets the natural grain remain part of the composition.',
  8500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut4-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut4-main.jpg',
  '["60 cm"]'::jsonb,
  '["Natural walnut"]'::jsonb,
  2,
  false,
  0,
  'Kashmiri walnut wood',
  'Kashmir, India',
  'Kashmiri Walnut Wood Carving',
  'Dust with a soft dry cloth. Keep away from water, direct sunlight and strong heat. Do not use household polish or abrasive cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Iris Carved Walnut Wall Panel | Poshkaar Kashmir',
  'Iris Carved Walnut Wall Panel, shaped and carved by hand in natural Kashmiri walnut wood.',
  'pending'
),
(
  'walnut-05',
  'Tree of the Valley Chinar Plaque',
  'walnut-05',
  'PKM-WALNUT-05',
  'Walnut Wood',
  'Walnut Wood',
  'Walnut Wood Carving',
  'A freestanding chinar-leaf plaque carved with a branching tree and textured foliage. The sculptural outline gives the small object presence on a console, bookshelf or gifting table.',
  5500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut5-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut5-main.jpg',
  '["38 cm"]'::jsonb,
  '["Natural walnut"]'::jsonb,
  3,
  false,
  0,
  'Kashmiri walnut wood',
  'Kashmir, India',
  'Kashmiri Walnut Wood Carving',
  'Dust with a soft dry cloth. Keep away from water, direct sunlight and strong heat. Do not use household polish or abrasive cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Tree of the Valley Chinar Plaque | Poshkaar Kashmir',
  'Tree of the Valley Chinar Plaque, shaped and carved by hand in natural Kashmiri walnut wood.',
  'pending'
),
(
  'walnut-06',
  'Gul Carved Walnut Hair Comb',
  'walnut-06',
  'PKM-WALNUT-06',
  'Walnut Wood',
  'Walnut Wood',
  'Walnut Wood Carving',
  'A crescent-shaped wide-tooth walnut comb finished with a hand-carved floral vine. Smooth rounded teeth and a polished grip make it a useful personal object with the warmth of Kashmir woodcraft.',
  2800,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut6-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/walnut-wood/walnut6-main.jpg',
  '["18 cm"]'::jsonb,
  '["Natural walnut"]'::jsonb,
  5,
  false,
  0,
  'Kashmiri walnut wood',
  'Kashmir, India',
  'Kashmiri Walnut Wood Carving',
  'Dust with a soft dry cloth. Keep away from water, direct sunlight and strong heat. Do not use household polish or abrasive cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Gul Carved Walnut Hair Comb | Poshkaar Kashmir',
  'Gul Carved Walnut Hair Comb, shaped and carved by hand in natural Kashmiri walnut wood.',
  'pending'
),
(
  'papier-01',
  'Noor Chinar Papier-Mâché Keepsake Box',
  'papier-01',
  'PKM-PAPIER-01',
  'Papier Mâché',
  'Papier Mâché',
  'Naqashi Painting',
  'A scalloped charcoal keepsake box covered in antique-gold chinar leaves and fine vine borders. The compact lacquered form is made for jewellery, small letters or considered gifting.',
  3800,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier1-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier1-main.jpg',
  '["15 cm"]'::jsonb,
  '["Hand-painted"]'::jsonb,
  5,
  true,
  0,
  'Papier mâché with hand-painted lacquer finish',
  'Kashmir, India',
  'Kashmiri Papier Mâché',
  'Dust gently with a soft dry cloth. Keep away from water, humidity, direct sunlight and sharp objects. Do not use household cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Noor Chinar Papier-Mâché Keepsake Box | Poshkaar Kashmir',
  'Noor Chinar Papier-Mâché Keepsake Box, shaped, lacquered and painted by hand in the Kashmiri naqashi tradition.',
  'pending'
),
(
  'papier-02',
  'Saffron Garden Papier-Mâché Box Pair',
  'papier-02',
  'PKM-PAPIER-02',
  'Papier Mâché',
  'Papier Mâché',
  'Naqashi Painting',
  'A coordinated pair of rounded keepsake boxes: one ivory garden pattern and one garnet chinar design. Their different sizes make the set useful for jewellery, mementos and wedding gifts.',
  5500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier2-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier2-main.jpg',
  '["Set of 2"]'::jsonb,
  '["Hand-painted"]'::jsonb,
  3,
  false,
  0,
  'Papier mâché with hand-painted lacquer finish',
  'Kashmir, India',
  'Kashmiri Papier Mâché',
  'Dust gently with a soft dry cloth. Keep away from water, humidity, direct sunlight and sharp objects. Do not use household cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Saffron Garden Papier-Mâché Box Pair | Poshkaar Kashmir',
  'Saffron Garden Papier-Mâché Box Pair, shaped, lacquered and painted by hand in the Kashmiri naqashi tradition.',
  'pending'
),
(
  'papier-03',
  'Zoon Garden Papier-Mâché Floor Vase',
  'papier-03',
  'PKM-PAPIER-03',
  'Papier Mâché',
  'Papier Mâché',
  'Naqashi Painting',
  'A tall floor vase with a long neck, generous shoulder and dense painted garden. Muted saffron, forest and rust details give the sculptural form a warm, collected character.',
  12500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier3-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier3-main.jpg',
  '["60 cm"]'::jsonb,
  '["Hand-painted"]'::jsonb,
  2,
  true,
  0,
  'Papier mâché with hand-painted lacquer finish',
  'Kashmir, India',
  'Kashmiri Papier Mâché',
  'Dust gently with a soft dry cloth. Keep away from water, humidity, direct sunlight and sharp objects. Do not use household cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Zoon Garden Papier-Mâché Floor Vase | Poshkaar Kashmir',
  'Zoon Garden Papier-Mâché Floor Vase, shaped, lacquered and painted by hand in the Kashmiri naqashi tradition.',
  'pending'
),
(
  'papier-04',
  'Guldaan Papier-Mâché Decorative Ewer',
  'papier-04',
  'PKM-PAPIER-04',
  'Papier Mâché',
  'Papier Mâché',
  'Naqashi Painting',
  'A lidded decorative ewer with a curved black handle, pouring spout and pedestal foot. Fine floral painting wraps the rounded body for an expressive shelf or table object.',
  8500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier4-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier4-main.jpg',
  '["45 cm"]'::jsonb,
  '["Hand-painted"]'::jsonb,
  2,
  false,
  0,
  'Papier mâché with hand-painted lacquer finish',
  'Kashmir, India',
  'Kashmiri Papier Mâché',
  'Dust gently with a soft dry cloth. Keep away from water, humidity, direct sunlight and sharp objects. Do not use household cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Guldaan Papier-Mâché Decorative Ewer | Poshkaar Kashmir',
  'Guldaan Papier-Mâché Decorative Ewer, shaped, lacquered and painted by hand in the Kashmiri naqashi tradition.',
  'pending'
),
(
  'papier-05',
  'Nigeen Miniature Papier-Mâché Trinket Box',
  'papier-05',
  'PKM-PAPIER-05',
  'Papier Mâché',
  'Papier Mâché',
  'Naqashi Painting',
  'A small round trinket box painted with coral and dusty-blue flowers around a central medallion. Its quiet ivory ground and fine brushwork suit rings, small keepsakes and guest gifting.',
  2800,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier5-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier5-main.jpg',
  '["12 cm"]'::jsonb,
  '["Hand-painted"]'::jsonb,
  6,
  false,
  0,
  'Papier mâché with hand-painted lacquer finish',
  'Kashmir, India',
  'Kashmiri Papier Mâché',
  'Dust gently with a soft dry cloth. Keep away from water, humidity, direct sunlight and sharp objects. Do not use household cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Nigeen Miniature Papier-Mâché Trinket Box | Poshkaar Kashmir',
  'Nigeen Miniature Papier-Mâché Trinket Box, shaped, lacquered and painted by hand in the Kashmiri naqashi tradition.',
  'pending'
),
(
  'papier-06',
  'Chinar Garden Papier-Mâché Box Quartet',
  'papier-06',
  'PKM-PAPIER-06',
  'Papier Mâché',
  'Papier Mâché',
  'Naqashi Painting',
  'Four graduated round and oval boxes brought together as a coordinated gift set. Each charcoal-lacquered lid carries a different floral medallion in muted turquoise, rust and gold.',
  7500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier6-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/papier-mache/papier6-main.jpg',
  '["Set of 4"]'::jsonb,
  '["Hand-painted"]'::jsonb,
  3,
  false,
  0,
  'Papier mâché with hand-painted lacquer finish',
  'Kashmir, India',
  'Kashmiri Papier Mâché',
  'Dust gently with a soft dry cloth. Keep away from water, humidity, direct sunlight and sharp objects. Do not use household cleaners.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Chinar Garden Papier-Mâché Box Quartet | Poshkaar Kashmir',
  'Chinar Garden Papier-Mâché Box Quartet, shaped, lacquered and painted by hand in the Kashmiri naqashi tradition.',
  'pending'
),
(
  'willow-01',
  'Crescent Willow Carry Basket',
  'willow-01',
  'PKM-WILLOW-01',
  'Willow Wicker',
  'Willow Wicker',
  'Willow Weaving',
  'A sculptural crescent basket whose broad curved rim becomes the handle. The close honey-toned weave is strong enough for daily carrying and elegant enough to leave on display.',
  3500,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/willow-wicker/willow1-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/willow-wicker/willow1-main.jpg',
  '["38 cm"]'::jsonb,
  '["Natural willow"]'::jsonb,
  5,
  true,
  0,
  'Natural willow with wood accents where shown',
  'Kashmir, India',
  'Kashmiri Willow Wicker',
  'Dust with a soft brush or dry cloth. Keep dry and well ventilated. Avoid prolonged sunlight, soaking and heavy loads beyond the stated use.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Crescent Willow Carry Basket | Poshkaar Kashmir',
  'Crescent Willow Carry Basket, woven by hand from carefully selected willow.',
  'pending'
),
(
  'willow-02',
  'Valley Willow Picnic Basket',
  'willow-02',
  'PKM-WILLOW-02',
  'Willow Wicker',
  'Willow Wicker',
  'Willow Weaving',
  'A low oval picnic basket with a tall arched handle, braided rim and fitted split lids. Its generous interior is designed for relaxed outings, gifting or useful home storage.',
  4800,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/willow-wicker/willow2-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/willow-wicker/willow2-main.jpg',
  '["45 cm"]'::jsonb,
  '["Natural willow"]'::jsonb,
  4,
  false,
  0,
  'Natural willow with wood accents where shown',
  'Kashmir, India',
  'Kashmiri Willow Wicker',
  'Dust with a soft brush or dry cloth. Keep dry and well ventilated. Avoid prolonged sunlight, soaking and heavy loads beyond the stated use.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Valley Willow Picnic Basket | Poshkaar Kashmir',
  'Valley Willow Picnic Basket, woven by hand from carefully selected willow.',
  'pending'
),
(
  'willow-03',
  'Lidded Willow Storage Basket',
  'willow-03',
  'PKM-WILLOW-03',
  'Willow Wicker',
  'Willow Wicker',
  'Willow Weaving',
  'A round woven storage basket framed by dark walnut-toned bands and a flat handled lid. The calm two-material finish works naturally in bedrooms, studies and living spaces.',
  4200,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/willow-wicker/willow3-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/willow-wicker/willow3-main.jpg',
  '["35 cm"]'::jsonb,
  '["Natural willow"]'::jsonb,
  4,
  false,
  0,
  'Natural willow with wood accents where shown',
  'Kashmir, India',
  'Kashmiri Willow Wicker',
  'Dust with a soft brush or dry cloth. Keep dry and well ventilated. Avoid prolonged sunlight, soaking and heavy loads beyond the stated use.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Lidded Willow Storage Basket | Poshkaar Kashmir',
  'Lidded Willow Storage Basket, woven by hand from carefully selected willow.',
  'pending'
),
(
  'willow-04',
  'Willow and Walnut Tissue Box Cover',
  'willow-04',
  'PKM-WILLOW-04',
  'Willow Wicker',
  'Willow Wicker',
  'Willow Weaving',
  'A rectangular tissue box cover that pairs close willow weaving with a dark wooden top and fine braided edges. It brings useful craft detail to a bedside, desk or washroom.',
  2200,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/willow-wicker/willow4-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/willow-wicker/willow4-main.jpg',
  '["25 cm"]'::jsonb,
  '["Natural willow"]'::jsonb,
  6,
  false,
  0,
  'Natural willow with wood accents where shown',
  'Kashmir, India',
  'Kashmiri Willow Wicker',
  'Dust with a soft brush or dry cloth. Keep dry and well ventilated. Avoid prolonged sunlight, soaking and heavy loads beyond the stated use.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Willow and Walnut Tissue Box Cover | Poshkaar Kashmir',
  'Willow and Walnut Tissue Box Cover, woven by hand from carefully selected willow.',
  'pending'
),
(
  'willow-05',
  'Valley Stripe Willow Market Basket',
  'willow-05',
  'PKM-WILLOW-05',
  'Willow Wicker',
  'Willow Wicker',
  'Willow Weaving',
  'An open oval market basket with two integrated handles and restrained forest and terracotta woven bands. The sturdy braided rim makes it practical for errands, storage and gifting.',
  3800,
  0,
  '["https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/willow-wicker/willow5-main.jpg"]'::jsonb,
  'https://sqqsrjcmsyctkujlzkmx.supabase.co/storage/v1/object/public/catalog-products/willow-wicker/willow5-main.jpg',
  '["40 cm"]'::jsonb,
  '["Natural willow"]'::jsonb,
  4,
  false,
  0,
  'Natural willow with wood accents where shown',
  'Kashmir, India',
  'Kashmiri Willow Wicker',
  'Dust with a soft brush or dry cloth. Keep dry and well ventilated. Avoid prolonged sunlight, soaking and heavy loads beyond the stated use.',
  'Dispatch timing is confirmed after current-piece photographs are approved',
  false,
  true,
  true,
  false,
  'active',
  true,
  'Valley Stripe Willow Market Basket | Poshkaar Kashmir',
  'Valley Stripe Willow Market Basket, woven by hand from carefully selected willow.',
  'pending'
)
on conflict (id) do update set
  title = excluded.title,
  slug = excluded.slug,
  sku = excluded.sku,
  category = excluded.category,
  collection = excluded.collection,
  embroidery_type = excluded.embroidery_type,
  description = excluded.description,
  price = excluded.price,
  compare_at_price = excluded.compare_at_price,
  images = excluded.images,
  image = excluded.image,
  sizes = excluded.sizes,
  colors = excluded.colors,
  stock = excluded.stock,
  is_bestseller = excluded.is_bestseller,
  material = excluded.material,
  origin = excluded.origin,
  craft = excluded.craft,
  care_instructions = excluded.care_instructions,
  lead_time = excluded.lead_time,
  made_to_order = excluded.made_to_order,
  ready_to_ship = excluded.ready_to_ship,
  limited_edition = excluded.limited_edition,
  one_of_one = excluded.one_of_one,
  status = excluded.status,
  published = excluded.published,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  photography_status = excluded.photography_status,
  updated_at = now();

notify pgrst, 'reload schema';

commit;

select
  count(*) as total_products,
  count(*) filter (where published and status = 'active') as live_products,
  count(*) filter (where price > 0) as products_with_prices,
  count(*) filter (where jsonb_array_length(images) > 0) as products_with_images
from public.products
where id like 'aari-%'
   or id like 'tilla-%'
   or id like 'dabka-%'
   or id like 'zari-%'
   or id like 'copper-%'
   or id like 'walnut-%'
   or id like 'papier-%'
   or id like 'willow-%';
